#!/bin/bash

set -e

if [[ -n "${STACTOOLS_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run code formatters in a docker container with all prerequisites installed.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker run --rm -it \
        -v `pwd`:/opt/stactools-nrcan-landcover \
        --entrypoint scripts/format \
        stacutils/stactools-nrcan-landcover:latest-dev
fi
